---

  name: NX1 Deploy - ExpressJS App
  run-name: Deploy example-expressjs-app to my environment by @${{ github.actor }}
  
  on:
    workflow_dispatch:
  
  permissions:
    id-token: write
    contents: read
  
  jobs:
    deploy:
      runs-on: ubuntu-latest
      name: NX1 Deploy
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: NX1 Prepare Deployment
          uses: nx1-io/app-copilot-action@main
          with:
            operation: 'prepare'
            app_id: 9b20993f-79df-4984-b1f1-756a929638ed
            env_id: c0b2b5f6-83df-4926-8ab4-8ee1dfaff869
            api_token: ${{ secrets.EXAMPLE_EXPRESS_JS }}
  
        - name: NX1 Assume Role
          uses: nx1-io/app-copilot-action@main
          with:
            operation: 'assume-role'
  
        - name: NX1 Deploy Service - expressjs-app
          uses: nx1-io/app-copilot-action@main
          with:
            operation: 'deploy'
            service: 'expressjs-app'
  
  # rev:1
  
          